### PR TITLE
Fixed the getcwd return that left the shell frozen when rm -rf

### PR DESCRIPTION
**Pull request by dbejar-s**

### CODE REVIEW

**Comment by pmarkaide** [comment]
I'm trying to test the rm, but this message appears

```minishell> mkdir -p test/test/test/test
minishell> cd test/test/test/test/
minishell> rm .
/usr/bin/rm: cannot remove '.': Is a directory
minishell> rm -r .
/usr/bin/rm: refusing to remove '.' or '..' directory: skipping '.'
minishell> pwd
/home/peitx/Omega/40-49.Study/42.Hive/Projects/3.minishell/test/test/test/test
minishell> rm -r ../..
/usr/bin/rm: refusing to remove '.' or '..' directory: skipping '../..'
```

Can you tell me how to test it?

**Comment by pmarkaide** [comment]
Also, I like the new short prompt with just minishell. But I prefer to show at least the last directory name. It's not important, we can discuss it tomorrow.

**Comment by dbejar-s** [comment]
We can customize the shell by showing or not showing the current directory, not a big deal.

**Comment by dbejar-s** [comment]
I sent you via Discord the main test for rm -rf. I haven't thought of deleting the same folder where you are with rm . 
I'm going to check what bash does. 
There are unlimited test cases.

**Comment by dbejar-s** [comment]
I'm going to merge this pull request, so I can work on the last version and create a branch from there.

**Pull request merged**
